/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Coin */

#ifndef _Included_Coin
#define _Included_Coin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Coin
 * Method:    probAlarm
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Coin_probAlarm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
