/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Probability */

#ifndef _Included_Probability
#define _Included_Probability
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Probability
 * Method:    probIncident
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_Probability_probIncident
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
